-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 12:37:01 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_generation_game_online
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_generation_game_online` ;
USE `db_generation_game_online` ;

-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_classe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_classe` (
  `class_id` INT NOT NULL AUTO_INCREMENT,
  `class_tipo` VARCHAR(45) NOT NULL,
  `class_habilidadeEspecial` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`class_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_generation_game_online`.`tb_personagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_generation_game_online`.`tb_personagem` (
  `character_id` INT NOT NULL AUTO_INCREMENT,
  `character_nome` VARCHAR(60) NOT NULL,
  `character_golpeFraco` VARCHAR(60) NOT NULL,
  `character_golpeForte` VARCHAR(45) NOT NULL,
  `tb_classe_class_id` INT NOT NULL,
  PRIMARY KEY (`character_id`, `tb_classe_class_id`),
  CONSTRAINT `fk_tb_personagem_tb_classe`
    FOREIGN KEY (`tb_classe_class_id`)
    REFERENCES `db_generation_game_online`.`tb_classe` (`class_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- EU TINHA ESQUECIDO QUE PRECISA DESSES ATRIBUTOS (ATAQUE E DEFESA)--
ALTER TABLE tb_personagem
DROP COLUMN character_golpeFraco,
DROP COLUMN character_golpeForte,
ADD COLUMN ataque BIGINT,
ADD COLUMN defesa BIGINT;







