-- MySQL Script generated by MySQL Workbench
-- Thu Apr 22 21:05:00 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_pizzaria_legal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_pizzaria_legal` DEFAULT CHARACTER SET utf8 ;
USE `db_pizzaria_legal` ;

-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_categoria` (
  `pk_categoria` INT NOT NULL AUTO_INCREMENT,
  `cate_tipo` VARCHAR(45) NOT NULL,
  `tb_tamanho` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`pk_categoria`)
);


-- -----------------------------------------------------
-- Table `db_pizzaria_legal`.`tb_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_pizzaria_legal`.`tb_pizza` (
  `pk_pizza` INT NOT NULL,
  `pizza_preco` FLOAT NOT NULL,
  `pizza_nome` VARCHAR(45) NOT NULL,
  `pizza_acompanhamento` VARCHAR(45) NOT NULL,
  `tb_categoria_pk_categoria` INT NOT NULL,
  PRIMARY KEY (`pk_pizza`, `tb_categoria_pk_categoria`),
  
  CONSTRAINT `fk_tb_pizza_tb_categoria`
    FOREIGN KEY (`tb_categoria_pk_categoria`)
    REFERENCES `db_pizzaria_legal`.`tb_categoria` (`pk_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
